<?php
    $idpage = $this->idpage;
    $config = $this->config;
?>
<div class="m-bottom">
	<div class="shopping-page">
		<form method="" action="">
			<div class="box-cart">
				<div class="row-cart row-cart-title">	
					<div class="col1">
						<span class="cart-black">THÔNG TIN KHÁCH ĐẶT HÀNG</span>
					</div>
					
				</div>
				<div class="form-info">
                    <!--
					<div class="box-avatar">
						<img src="images/avatar.jpg" alt="" title=""/>
					</div>
                    -->
					<div class="type-info">
						<div class="row-info">
							<div class="title">Họ và Tên<span class="red">*</span></div>
							<input type="text" id="name" name="name" value="<?php echo $this->name; ?>" />
						</div>
						<div class="row-info">
							<div class="title">Số điện thoại<span class="red">*</span></div>
							<input type="text" id="phone" name="phone" value="<?php echo $this->phone; ?>" />
						</div>
						<div class="row-info">
							<div class="title">Email<span class="red">*</span></div>
							<input type="text" id="email" name="email" value="<?php echo $this->email; ?>" />
						</div>
						<div class="row-info info-place">
							<div class="title">NƠI NHẬN HÀNG</div>
							<div class="dot"></div>
						</div>
						<div class="row-info">
							<div class="title">Thành phố<span class="red">*</span></div>
							<select name="city" id="city">
								<option value="">Tỉnh/Thành phố</option>
								<option value="an-giang">An Giang</option>
								<option value="baria-vungtau">Bà Rịa - Vũng Tàu</option>
								<option value="bac-giang">Bắc Giang</option>
								<option value="bac-kan">Bắc Kạn</option>
								<option value="bac-lieu">Bạc Liệu</option>
								<option value="bac-ninh">Bắc Ninh</option>
								<option value="ben-tre">Bến Tre</option>
								<option value="binh-dinh">Bình Định</option>
								<option value="binh-duong">Bình Dương</option>
								<option value="binh-phuoc">Bình Phước</option>
								<option value="binh-thuan">Bình Thuận</option>
								<option value="ca-mau">Cà Mau</option>
								<option value="cao-bang">Cao Bằng</option>
								<option value="dak-lak">Đắk Lắk</option>
								<option value="dak-nong">Đắk Nông</option>
								<option value="dien-bien">Điện Biên</option>
								<option value="dong-nai">Đồng Nai</option>
								<option value="dong-thap">Đồng Tháp</option>
								<option value="gia-lai">Gia Lai</option>
								<option value="ha-giang">Hà Giang</option>
								<option value="ha-nam">Hà Nam</option>
								<option value="ha-tinh">Hà Tĩnh</option>
								<option value="hai-duong">Hải Dương</option>
								<option value="hau-giang">Hậu Giang</option>
								<option value="hoa-binh">Hoà Bình</option>
								<option value="hung-yen">Hưng Yên</option>
								<option value="khanh-hoa">Khánh Hoà</option>
								<option value="kien-giang">Kiên Giang</option>
								<option value="kon-tum">Kon Tum</option>
								<option value="lai-chau">Lai Châu</option>
								<option value="lam-dong">Lâm Đồng</option>
								<option value="lang-son">Lạng Sơn</option>
								<option value="lao-cai">Lào Cai</option>
								<option value="long-an">Long An</option>
								<option value="nam-dinh">Nam Định</option>
								<option value="nghe-an">Nghệ An</option>
								<option value="ninh-binh">Ninh Bình</option>
								<option value="ninh-thuan">Ninh Thuận</option>
								<option value="phu-tho">Phú Thọ</option>
								<option value="quang-binh">Quảng Bình</option>
								<option value="quang-nam">Quảng Nam</option>
								<option value="quang-ngai">Quảng Ngãi</option>
								<option value="quang-ninh">Quảng Ninh</option>
								<option value="quang-tri">Quảng Trị</option>
								<option value="soc-trang">Sóc Trăng</option>
								<option value="son-la">Sơn La</option>
								<option value="tay-ninh">Tây Ninh</option>
								<option value="thai-binh">Thái Bình</option>
								<option value="thai-nguyen">Thái Nguyên</option>
								<option value="thanh-hoa">Thanh Hoá</option>
								<option value="thua-thien-hue">Thừa Thiên Huế</option>
								<option value="tien-giang">Tiền Giang</option>
								<option value="tra-vinh">Trà Vinh</option>
								<option value="tuyen-quang">Tuyên Quang</option>
								<option value="vinh-long">Vĩnh Long</option>
								<option value="vinh-phuc">Vĩnh Phúc</option>
								<option value="yen-bai">Yên Bái</option>
								<option value="phu-yen">Phú Yên</option>
								<option value="can-tho">Cần Thơ</option>
								<option value="da-nang">Đà Nẵng</option>
								<option value="hai-phong">Hải Phòng</option>
								<option value="ha-noi">Hà Nội</option>
								<option value="tphcm">Tp Hồ Chí Minh</option>
							</select>
						</div>
						<div class="row-info">
							<div class="title">Quận<span class="red">*</span></div>
							<input type="text" id="district" name="district" value="<?php echo $this->district; ?>" />
							<!--<select name="district" id="district">
								<option value="">Quận/Huyện</option>
								<option value="Quan1">Quận 1</option>
								<option value="Quan2">Quận 2</option>
							</select>-->
						</div>
						<div class="row-info">
							<div class="title">Địa chỉ<span class="red">*</span></div>
							<input type="text" id="address" name="address" value="<?php echo $this->address; ?>" />
						</div>
                        <div class="row-info">
							<div class="title">Ghi chú<span class="red"></span></div>
							<textarea id="comment" name="comment"></textarea>
						</div>
						
						<div class="btn-muahang">
                            <input type="hidden" id="idpage" value="<?php echo $this->idpage ?>" />
							<input type="hidden" id="isfbuser" value="<?php echo $this->isfbuser ?>" />
							<input type="hidden" id="linkfb" value="<?php echo $this->linkfb ?>" />
							<input type="hidden" id="idfb" value="<?php echo $this->idfb ?>" />
							<input name="button-dathang" type="button" value="Mua hàng"/>
                            <p class="message"></p>
						</div>
					</div>
				</div>
			</div>
		</form>
		<div class="info-delivery">
			<div class="title-others">
				<div class="dotted"></div>
				<div class="title">Thông tin giao hàng</div>
			</div>
			<div class="info">
				<?php echo $config['delivery'] ?>
				<br/><br/>
				Điện thoại: <span style="color:#053443;"><?php echo $config['phone'] ?></span><br/>
				Email: <span style="color:#053443;"><?php echo $config['emailfrom'] ?></span>
			</div>
		</div>
		<div class="clear"></div>
	</div>
	<div class="cart-shop">
		<div class="cart-icon-right">
			<a href="<?php echo APP_DOMAIN .'/giohang?idpage='. $idpage ?>" class="cart-icon">
				<div class="total"><?php echo isset($_SESSION["cart_$idpage"]) ? count($_SESSION["cart_$idpage"]) : "0" ?></div>
			</a>
			<a href="#" class="search-icon"></a>
			<div class="search-content">
				<input onkeyup="searchProduct(event, this.value)" type="text" value="" placeholder="Tìm kiếm" />
			</div>
			
			<a href="javascript:void(0);" class="gotoTop"></a>
		</div>
	</div>
	<!--End product-->
</div>