<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://opengraphprotocol.org/schema/"><head>
        <title>APPS STORE</title>  
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<script>
			var taaa = {};
			taaa.appdomain = "<?php echo APP_DOMAIN ?>";
			taaa.fbappdomain = "<?php echo FB_APP_DOMAIN ?>";
		</script>
		<?php
			echo $this->headLink ()
					// ->appendStylesheet ( $this->baseUrl ('public/css/style.css'))
					->appendStylesheet ( $this->baseUrl ('application/templates/giaodien_admin/style.css'))
					->appendStylesheet ( $this->baseUrl ('application/templates/giaodien_admin/css/custom.css'))
					;
					
		
			echo $this->headScript ()
					->appendFile ( $this->baseUrl ('/application/templates/giaodien_admin/js/jquery-1.8.0.min.js') )
                    
					->appendFile ( $this->baseUrl ('/application/templates/giaodien_admin/js/script.js') )
					->appendFile ( $this->baseUrl ('/application/templates/giaodien_admin/js/aj.js') )

					->appendFile ( $this->baseUrl ('/public/ckeditor/ckeditor.js') )
					//->appendFile ( $this->baseUrl ('/public/ckfinder/ckfinder.js') )
                    ->appendFile ( $this->baseUrl ('/public/tinymce/js/tinymce/tinymce.min.js') )
				
					;
				
		?>
        
		<script>
            $(function(){
              center()//gọi hàm mới load web
                $(window).resize(function(){center()})//gọi hàm khi resize
        		//alert($(window).width());
        		//alert($('#thongbao').width());
              function center(){
                $('#thongbao').css({left:($(window).width()-$('#thongbao').width())/2,top:150});
                $('#popup_content').css({left:($(window).width()-$('#popup_content').width())/2,top:100})
              }
            });
            scrollToTop();                        
          </script>
    <style>
        body{min-height:800px !important}
    </style>
	</head>
    <body>
	<div id="bg_thongbao"></div>
	<div id="thongbao"></div>
    <div id="popup_content">
        <div id="popup_content" style="left: 306.5px; top: 100px;">        
            <div class="header_popup_content">
                Chi tiết đơn hàng DH14_00001            
                <p onclick="close_popup()" class="close_popup">X</p>
            </div>
            <div class="popup_content">
                <p class="select_album_fb">
                    chọn Album: 
                    <select>
                        <option value="ko">Chọn Album</option>
                    </select>
                    <input type="submit" name="Chọn" value="Chọn" />
                </p>
                
                <div class="list_image_fb">
                    <ul class="ul_list_img_fb">
                        <li class="last">
                            <label>
                            <p class="img_fb">
                                <img src="http://localhost/appfb/apps-store/application/layouts/tmpstore/images/upload/images/1363321950_smn5.jpg" alt="" title="" />
                                <input type="checkbox" name="list_main_image[]" value="" />
                            </p>
                            
                            </label>
                        </li>
                    </ul>
                </div>
            </div><!--End popup_content-->
        </div><!--End popup_content-->
    </div><!--End popup_content-->
    
    <?php  echo $this->render('_header.phtml')?>
        <div class="content">
    		<div id='quanlidanhsachtrang' class="home-page">
                <?php echo $this->layout()->content; ?>	
    		</div>
    	</div>
    </div>
    
    <div id="fb-root"></div>
    <script src="https://connect.facebook.net/en_US/all.js"></script>
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId : '', //Your facebook APP here
          cookie : true // enable cookies to allow the server to access the session
        });
      }
      window.onload = function() {
        FB.Canvas.setAutoGrow(91);
      }
      
      (function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
</body>
</html>	
