<?php 
    $maxvitri = $this->maxvitri +1;
    $list_loaisp = $this->list_loaisp;
?>
<div class="commonpage">
	<form action="addcategory/themloaisp" method="post">
		<div class="pageconfig">
			<div class="row">
				<div class="title">Thuộc danh mục</div>
				<div class="ip">
                    <select id="parent_id" style="border: 1px solid #909090; height: 24px; padding: 2px;">
                        <option value="0">Không thuộc danh mục nào</option>
                        <?php
                            foreach($list_loaisp as $key=>$value)
                            {
                                echo "<option value='{$value['idloaisp']}'>{$value['tenloaisp']}</option>";
                            }
                        ?>
                    </select>
                </div>
			</div>
			<div class="row">
				<div class="title">Tên loại sản phẩm</div>
				<div class="ip"><input class="inputstyle" type="text" name="tenlsp" id="tenlsp"/></div>
			</div>
			<div class="row">
				<div class="title">Vị trí</div>
				<div class="ip"><input class="inputstyle" type="text" name="vitri" id="vitri" value="<?php echo $maxvitri ?>"/></div>
			</div>
			<div class="row">
				<div class="title">Hiển thị</div>
				<div class="ip"><input type="checkbox" value="1" checked="checked" name="anhien" id="anhien" /> (bỏ chọn để ẩn loại sản phẩm này)</label></div>
			</div>
			<div class="btn">
                <input type="button" name="" value="Thêm Loại Sản Phẩm" onclick = "ThemLoaiSanPham(document.getElementById('parent_id').value, document.getElementById('tenlsp').value, document.getElementById('vitri').value, document.getElementById('anhien').checked)"/>
                <input type="button" onclick="top.location.href = '<?php echo ROOT_DOMAIN ?>/admin/category'" value="Quay lại" />
			</div>
	      </div>
      </form>
   <div class="clear"></div>
</div>




















