<?php 
    $category = $this->category;
    $list_loaisp = $this->list_loaisp;
    //print_r($category);
?>

<div class="commonpage">
	<form action="addcategory/themloaisp" method="post">
		<div class="pageconfig">
			<div class="row">
				<div class="title">Loại sản phẩm cha</div>
				<div class="ip">
                    <select name="parent_id" id="parent_id" style="border: 1px solid #909090; height: 24px; padding: 2px;">
                        <option value="0">Không thuộc loại sản phẩm cha nào</option>
                        <?php
                            foreach($list_loaisp as $key=>$value)
                            {
                                $selected = "";
                                $selected = $category[0]['parent_id'] == $value['idloaisp'] ? "selected='selected'" : "";
                                echo "<option $selected value='{$value['idloaisp']}'>{$value['tenloaisp']}</option>";
                            }
                        ?>
                    </select>
                </div>
			</div>
			<div class="row">
				<div class="title">Tên loại sản phẩm</div>
				<div class="ip"><input class="inputstyle" type="text" name="tenlsp" id="tenlsp" value="<?php echo $category[0]['tenloaisp'] ?>"/></div>
			</div>
			<div class="row">
				<div class="title">Vị trí</div>
				<div class="ip"><input class="inputstyle" type="text" name="vitri" id="vitri" value="<?php echo $category[0]['vitri'] ?>"/></div>
			</div>
			<div class="row">
				<div class="title">Hiển thị</div>
				<div class="ip"><label><input type="checkbox" value="" name="anhien" id="anhien" <?php if($category[0]['anhien']==1) echo "checked='checked'"; ?> /> (bỏ chọn để ẩn loại sản phẩm này)</label></div>
			</div>
			<div class="btn">
                <input type="hidden" id="idcategory" value="<?php echo $category[0]['idloaisp'] ?>"/>
                <input type="button" name="btnsubmitt" value="Cập Nhật Loại Sản Phẩm" onclick = "CapNhatLoaiSanPham(document.getElementById('parent_id').value, document.getElementById('idcategory').value, document.getElementById('tenlsp').value, document.getElementById('vitri').value, document.getElementById('anhien').checked)" />
                <input type="button" onclick="top.location.href = '<?php echo ROOT_DOMAIN ?>/admin/category'" value="Quay lại" />
			</div>
	      </div>
      </form>
   <div class="clear"></div>
</div>





