<?php
	
	$checkSessionIdpage = $this->checkSessionIdpage;
	if($checkSessionIdpage == 0)
	{
		echo "<center style='color:#41BBDE; padding:20px 0px'>Chọn Page cần thao tác</center>";
	}
	else
	{
		$category = $this->category;

?>

<div class="commonpage notborder product-page">
	<table class="tbl-home" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<th width="5%">Stt</th>
			<th width="10%">Vị trí</th>
			<th width="40%">Tên loại sản phẩm</th>
			<th width="15%">Hiển thị</th>
			<th width="15%">Công cụ</th>
		</tr>
        <?php
            $parent_order = 0;
                for($i=0; $i<count($category); $i++)
                {
                    $parent_order = $category[$i]['parent_id'] == 0 ? $category[$i]['vitri'] : $parent_order;
                    $order = $category[$i]['parent_id'] == 0 ? $category[$i]['vitri'] : $parent_order .'.'. $category[$i]['vitri'];
            ?>
    		<tr>
        		<td><?php echo $i+1; ?></td>
                <td><strong><?php echo $order ?></strong></td>
        		<td style="text-align: left; padding: 2px;"><a href="category/detail?idcat=<?php echo base64_encode($category[$i]['idloaisp']) ?>"><?php echo $category[$i]['tenloaisp'] ?></a></td>
                <td>
                    <?php if ($category[$i]['anhien']==1){?>
                        <img src="<?php echo APP_DOMAIN . '/application/templates/giaodien_admin/images/tick.png' ?>" alt="hiện" title="Lọai sản phẩm này đã được hiển thị"/>
                    <?php } else {?>
                        <img src="<?php echo APP_DOMAIN . '/application/templates/giaodien_admin/images/publish.png' ?>" alt="ẩn" title="Lọai sản phẩm này đã được hiển thị"/>
                    <?php } ?>
                </td>
                <td>
        			<a href="category/detail?idcat=<?php echo base64_encode($category[$i]['idloaisp']) ?>"><img src="<?php echo APP_DOMAIN . '/application/templates/giaodien_admin/images/setting.png' ?>" alt="ct" title="Chi Tiết Sản Phẩm"/></a>
                    <a onclick="delete_category('<?php echo base64_encode($category[$i]['idloaisp']) ?>')" href="javascript:void(0);"><img src="<?php echo APP_DOMAIN . '/application/templates/giaodien_admin/images/delete.png' ?>" alt="xoa" title="Xóa Sản Phẩm"/></a>
        		</td>
  	       </tr>
        <?php } ?>
	</table>
    <a class="add" href="category/add">Thêm loại sản phẩm mới</a>
    <div class="clear"></div>
</div>
<?php
    }
?>