<?php
    $category = $this->category;
    $donvitien = $this->donvitien;
?>
<form id="form_add_product">
<table class="table_select_danhmuc" width="100%">
    <tr>
        <td  style="border: none;">
            Thuộc danh mục
            <select class="select_parent_cat" name="select_parent_cat">
                <option value="ko">Chọn danh mục</option>
                <?php
                    foreach($category as $k=>$v)
                    {
                        echo "<option value='{$v['idloaisp']}'>{$v['tenloaisp']}</option>";
                    }
                ?>
            </select><span style="color: red;">(*)</span>
        </td>
        <td  style="border: none;">
            <p class="p_select_child_cat">
                Thuộc danh mục con
                <select class="select_child_cat" name="select_child_cat">
                    <option value="ko">Chọn danh mục</option>
                </select><span style="color: red;">(*)</span>
            </p>
        </td>
    </tr>
</table>
<p>
    <input disabled='disabled' type="button" name="btn_get_image_on_fb" value="Tải hình" onclick="download_photo_fb('add')" />
</p>
<table width='100%' class="show_photo_fb">

    <tr>
        <td align='center' width='5%'>STT</td>
        <td align='center' width='10%'>Hình</td>
        <td align='center' width='35%'>Tên SP<span style="color: red;">(*)</span></td>
        <td align='center' width='10%'>Giá tiền (<?php echo $donvitien ?>)</td>
        <td align='center' width='35%'>Mô tả</td>
        <td align='center' width='15%'>Xóa</td>
    </tr>
<!--
    <tr>
        <td align='center'>1</td>
        <td align='center'><img class="img_sp" src="http://sphotos-c.ak.fbcdn.net/hphotos-ak-prn2/t1/1901432_364063010400949_1191853405_n.jpg" alt="" title=""/></td>
        <td align='center'><input class="name_sp" type="text" name="name" value="" /></td>
        <td align='center'><input class="price_sp" type="text" name="price" value="" /></td>
        <td align='center'><textarea class="des_sp" name="description"></textarea></td>
        <td align='center'>
            <a href=""><img src="<?php echo APP_DOMAIN . '/application/templates/giaodien_admin/images/chitiet.png' ?>" alt="ct" title="Chi Tiết Sản Phẩm"/></a>
			<a href="javascript:;" ><img src="<?php echo APP_DOMAIN . '/application/templates/giaodien_admin/images/xoa.png' ?>" alt="xoa" title="Xóa Sản Phẩm"/></a>
        </td>
    </tr>
-->
</table>
<input type="button" name="save_add_product" value="Lưu" />
</form>













