<?php
    $idpage = $this->idpage;
    $config = $this->config;
?>
<div class="m-bottom">
	<div class="shopping-page">
		<form method="" action="">
			<div class="box-cart">
				<div class="row-cart row-cart-title">	
					<div class="col1">
						<span class="cart-black">THÔNG TIN KHÁCH ĐẶT HÀNG</span>
					</div>
					
				</div>
				<div class="form-info">
                    <!--
					<div class="box-avatar">
						<img src="images/avatar.jpg" alt="" title=""/>
					</div>
                    -->
					<div class="type-info">
						<div class="row-info">
							<div class="title">Họ và Tên<span class="red">*</span></div>
							<input type="text" id="name" name="name" value="" />
						</div>
						<div class="row-info">
							<div class="title">Số điện thoại<span class="red">*</span></div>
							<input type="text" id="phone" name="phone" value="" />
						</div>
						<div class="row-info">
							<div class="title">Email<span class="red">*</span></div>
							<input type="text" id="email" name="email" value="" />
						</div>
						<div class="row-info info-place">
							<div class="title">NƠI NHẬN HÀNG</div>
							<div class="dot"></div>
						</div>
						<div class="row-info">
							<div class="title">Thành phố<span class="red">*</span></div>
							<select name="city" id="city">
								<option value="">Tỉnh/Thành phố</option>
								<option value="HCM">Hồ Chí Minh</option>
								<option value="HaNoi">Hà nội</option>
							</select>
						</div>
						<div class="row-info">
							<div class="title">Quận<span class="red">*</span></div>
							<select name="district" id="district">
								<option value="">Quận/Huyện</option>
								<option value="Quan1">Quận 1</option>
								<option value="Quan2">Quận 2</option>
							</select>
						</div>
						<div class="row-info">
							<div class="title">Địa chỉ<span class="red">*</span></div>
							<input type="text" id="address" name="address" value="" />
						</div>
                        <div class="row-info">
							<div class="title">Ghi chú<span class="red"></span></div>
							<textarea id="comment" name="comment"></textarea>
						</div>
						
						<div class="btn-muahang">
                            <input type="hidden" id="idpage" value="<?php echo $this->idpage ?>" />
							<input name="button-dathang" type="button" value="Mua hàng"/>
                            <p class="message"></p>
						</div>
					</div>
				</div>
			</div>
		</form>
		<div class="info-delivery">
			<div class="title-others">
				<div class="dotted"></div>
				<div class="title">Thông tin giao hàng</div>
			</div>
			<div class="info">
				<?php echo $config['delivery'] ?>
				<br/><br/>
				Điện thoại: <span style="color:#053443;"><?php echo $config['phone'] ?></span><br/>
				Email: <span style="color:#053443;"><?php echo $config['emailfrom'] ?></span>
			</div>
		</div>
		<div class="clear"></div>
	</div>
	<div class="cart-shop">
		<div class="cart-icon-right">
			<a href="<?php echo APP_DOMAIN .'/giohang?idpage='. $idpage ?>" class="cart-icon">
				<div class="total"><?php echo isset($_SESSION["cart_$idpage"]) ? count($_SESSION["cart_$idpage"]) : "0" ?></div>
			</a>
			<a href="#" class="search-icon"></a>
			<div class="search-content">
				<input onkeyup="searchProduct(event, this.value)" type="text" value="" placeholder="Tìm kiếm" />
			</div>
			
			<a href="javascript:void(0);" class="gotoTop"></a>
		</div>
	</div>
	<!--End product-->
</div>