<?php
	$checkSessionIdpage = $this->checkSessionIdpage;
	if($checkSessionIdpage == 0)
	{
		echo "<center><img  src='".APP_DOMAIN."/application/templates/giaodien_admin/images/chon page.jpg'/></center>";
	}
	else
	{
		$product = $this->product;
		$category = $this->category;
		$donvitien = $this->donvitien;
        $idpage = $this->idpage;
        $store = App_Models_StoreModel::getInstance();
?>
<input type="button" name="themspmoi" value="Thêm Sản Phẩm Mới" onclick="window.location.href='product/add'"/><br />
<p class="search_parent_cat">
<span>Chọn danh mục </span>
<select onchange="SearchCategory(this.value)" style="height:25px; padding:4px">
    <option value="-1">Chọn danh mục</option>
    <option value="0">Xem Tất Cả</option>
    <?php 
        for($i=0; $i<count($category); $i++)
        {
            if(@$_GET['idcat'] == $category[$i]['idloaisp'])
                echo "<option selected='selected' value='". $category[$i]['idloaisp'] ."'>". $category[$i]['tenloaisp'] ."</option>";
            else
                echo "<option value='". $category[$i]['idloaisp'] ."'>". $category[$i]['tenloaisp'] ."</option>";
        }
    ?>
</select>
</p>
<?php
    if(isset($_GET['idcat']))
    {
    $idcat = $_GET['idcat'];
    $sql = "select idloaisp, tenloaisp from ishali_loaisp where parent_id = '$idcat' and idpage = '$idpage' ORDER BY vitri";
    $child_cat = $store->SelectQuery($sql);
    //print_r($child_cat);
?>
<p class="search_child_cat">
<span>Chọn danh mục con</span>
<select style="height:25px; padding:4px">
    <option value="-1">Chọn danh mục con</option>
    <option value="0">Xem Tất Cả</option>
    <?php
        $idchildcat = "";
        if(isset($_GET['idchildcat']))
        {
            $idchildcat = $_GET['idchildcat'];
        }
        foreach($child_cat as $k=>$v)
        {
            $selected = "";
            $selected = $v['idloaisp'] == $idchildcat ? "selected = 'selected'" : "";
            echo "<option $selected value='{$v['idloaisp']}'>{$v['tenloaisp']}</option>";
        }
    ?>
</select>
</p>
<?php
    }
?>
<p class="search_product">
	<span>Tìm kiếm</span>
	<input onkeyup="searchProduct(event, this.value)" type="text" value="" placeholder="Tìm kiếm" />
</p>

<table class="spdg" border="1">
	<tr>
		<th width="20">STT</th>
        <th width="40" align="center">Hình ảnh</th>
		<th width="120">Tên</th>
        <th width="50">Giá (<?php echo $donvitien ?>)</th>
        <th width="90">Danh mục</th>
        <th width="20">Mới</th>
        <th align='center' width="70">Giá sau khi giảm (<?php echo $donvitien ?>)</th>
        <th width="20">Sử dụng</th>
		<th width="30">Công Cụ</th>
	</tr>
    <?php 
		if($product != null){
			for($i=0; $i<count($product); $i++)
			{
				$danhmuc = ($product[$i]['tenloaisp_parent'] == "") ? $product[$i]['tenloaisp'] : $product[$i]['tenloaisp_parent'] .' >> '. $product[$i]['tenloaisp'];
	?>
	<tr>
		<td align="center"><?php echo $i+1 ?></td>
		<td align="center"><img class="hinhchinh_product" src="<?php echo $product[$i]['hinhchinh'] ?>" /></td>
		<td><a href="product/detail?idsp=<?php echo base64_encode($product[$i]['idsp']) ?>"><?php echo $product[$i]['tensp'] ?></a></td>
		<td><?php echo number_format($product[$i]['gia'],0,',','.') ?></td>
		<td><?php echo $danhmuc ?></td>
		<td align="center">
			<?php if ($product[$i]['spmoi'] == 1){?>
				<img src="<?php echo APP_DOMAIN . '/application/templates/giaodien_admin/images/tick.png' ?>" alt="hiện" title="Sản phẩm này đang ở trạng thái (Mới)"/>
			<?php }?> 
		</td>
		<td align='center'>
			<?php echo ($product[$i]['giagiam'] != 0) ? number_format($product[$i]['giagiam'],0,',','.') .'<br/>'. '<em>(giảm '. $product[$i]['sale_off'] .'%)</em>': "<img src='". APP_DOMAIN . "/application/templates/giaodien_admin/images/publish.png" ."' alt='Sản phẩm không giảm giá' title='Sản phẩm này không giảm giá'/>"; ?>
			
		</td>
		<td align="center">
			<?php if ($product[$i]['anhien'] == 1){?>
				<img src="<?php echo APP_DOMAIN . '/application/templates/giaodien_admin/images/tick.png' ?>" alt="hiện" title="Sản phẩm này đang được hiển thị"/>
			<?php } else {?>
				<img src="<?php echo APP_DOMAIN . '/application/templates/giaodien_admin/images/publish.png' ?>" alt="ẩn" title="Sản phẩm này không được hiển thị"/>
			<?php } ?>
		</td>
		
		<td align="center">
			<a href="product/detail?idsp=<?php echo base64_encode($product[$i]['idsp']) ?>"><img src="<?php echo APP_DOMAIN . '/application/templates/giaodien_admin/images/sua.png' ?>" alt="ct" title="Chi Tiết Sản Phẩm"/></a>
			<a href="javascript:;" onclick = "DeleteProduct(<?php echo $product[$i]['idsp'] ?>)"><img src="<?php echo APP_DOMAIN . '/application/templates/giaodien_admin/images/xoa.png' ?>" alt="xoa" title="Xóa Sản Phẩm"/></a>
		</td>
	</tr>
	  <?php } 
		} 
		else { 
			echo '<tr><td colspan=9 align="center">Không tìm thấy sản phẩm</td></tr>';
		}
	  ?>

</table>
<input type="button" name="themspmoi" value="Thêm Sản Phẩm Mới" onclick="window.location.href='product/add'"/>
<?php } ?>