<script>
	$(document).ready(function(e) {
	    Products.init();
	    $('.jqzoom').jqzoom({
            zoomType: 'innerzoom',
            lens:true,
            preloadImages: false,
            alwaysOn:false
        });
	});
</script>
<div class="m-top">
	<!--breadcrum-->
	<div class="breadcrum">
		<a href="#">Hàng mới</a> / <a href="#">Quần áo</a> / <a href="#">Nữ</a>/
		<a href="#" class="">Áo</a> / 
		<a href="#" class="active">Áo CHIBI Japanese</a>
	</div>
	<!--End breadcrum-->
	
</div>
<div class="m-bottom">
	<!--product-->
	<div class="product">
		 <div class="slidedetails">
		 	<!--slideshow-->
        	<div id="slideshow">
            	 
				<div id="jslidernews2" class="lof-slidecontent" style="width:345px; height:307px;">
                    
		    		 <!-- MAIN CONTENT --> 
		              <div class="main-slider-content">
		              	<div class="button-previous">Previous</div>
             			<div class="button-next">Next</div>
		                <div class="sliders-wrapper">
		                	
		                	<ul class="sliders-wrap-inner">
				                 <li>
			                          <div class="bd-around">
			                          		<a href="<?php echo APP_DOMAIN . '/application/layouts/bookshop/'?>images/s-1-big.jpg" class="jqzoom" rel=''  title="" >
									            <img src="<?php echo APP_DOMAIN . '/application/layouts/bookshop/'?>images/s-1.jpg"  title="triumph"  style="">
									        </a>
			                          </div>           
			                        
			                    </li> 
			                    <li>
			                          <div class="bd-around"><a href="<?php echo APP_DOMAIN . '/application/layouts/bookshop/'?>images/s-2.jpg" class="jqzoom"><img src="<?php echo APP_DOMAIN . '/application/layouts/bookshop/'?>images/s-2.jpg" alt=""/></a></div>           
			                         
			                    </li> 
			                     <li>
			                          <div class="bd-around"><a href="<?php echo APP_DOMAIN . '/application/layouts/bookshop/'?>images/s-3.jpg" class="jqzoom"><img src="<?php echo APP_DOMAIN . '/application/layouts/bookshop/'?>images/s-3.jpg" alt=""/></a></div> 
			                         
			                    </li> 
			                     <li>
			                         <div class="bd-around"><a href="<?php echo APP_DOMAIN . '/application/layouts/bookshop/'?>images/s-1.jpg" class="jqzoom"><img src="<?php echo APP_DOMAIN . '/application/layouts/bookshop/'?>images/s-1.jpg" alt=""/></a></div>
			                         
			                    </li> 
			                     <li>
			                          <div class="bd-around"><a href="<?php echo APP_DOMAIN . '/application/layouts/bookshop/'?>images/s-2.jpg" class="jqzoom"><img src="<?php echo APP_DOMAIN . '/application/layouts/bookshop/'?>images/s-2.jpg" alt=""/></a></div>       
			                         
			                    </li> 
		                  </ul>
		                  </div>  	
		            </div>
		 		   <!-- END MAIN CONTENT --> 
		           <!-- NAVIGATOR -->
		           	<div class="navigator-content">
		           		
		                  <div class="navigator-wrapper">
		                        <ul class="navigator-wrap-inner">
			                        <li class="">
		                                <div>
		                                   <img src="<?php echo APP_DOMAIN . '/application/layouts/bookshop/'?>images/s-1.jpg" alt=""/> 
		                                </div>    
		                            </li>
		                            <li class="">
		                                <div>
		                                    <img src="<?php echo APP_DOMAIN . '/application/layouts/bookshop/'?>images/s-2.jpg" alt=""/>
		                                </div>    
		                            </li>
		                            <li class="">
		                                <div>
		                                    <img src="<?php echo APP_DOMAIN . '/application/layouts/bookshop/'?>images/s-3.jpg" alt=""/>
		                                </div>    
		                            </li>
		                            <li class="">
		                                <div>
		                                   <img src="<?php echo APP_DOMAIN . '/application/layouts/bookshop/'?>images/s-1.jpg" alt=""/> 
		                                </div>    
		                            </li>
		                            <li class="">
		                                <div>
		                                   <img src="<?php echo APP_DOMAIN . '/application/layouts/bookshop/'?>images/s-2.jpg" alt=""/> 
		                                </div>    
		                            </li>
		                        </ul>
		                  </div>
		   
		             </div>
		             
		              <!-- BUTTON PLAY-STOP -->
		              <div class="button-control action-start hover-stop" style="display:none;"></div>
		          <!-- END OF BUTTON PLAY-STOP -->     
				</div>  
	       </div>
	        <!--slideshow -->	
		</div>
		<div class="right-product">
			<!--likethis-->
			<div class="likethis">
				<div class="buynow"><a href="#">Mua</a></div>
				<div class="fb-like" data-href="http://abc.html" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></div>
			</div>
			<!--End likethis-->
			<!--product-description-->
			<div class="product-description">
				<div class="row_desc">
					<div class="title">Áo CHIBI CHUCHO</div>
					
				</div>
				<div class="row_desc">
					<div class="title">50.000 đ</div>
				</div>
				<div class="row_desc">
					<div class="title">Số lượng:</div>
					<div class="desc">
						<select name="amount" class="select">
							<option value="1">1</option>
							<option value="2">2</option>
							<option value="3">3</option>
						</select>
					</div>
				</div>
				<div class="row_desc">
					<div class="title">Size:</div>
					<div class="desc">
						<select name="size" class="select">
							<option value="M">M</option>
							<option value="L">L</option>
							<option value="S">S</option>
						</select>
					</div>
				</div>
				
				<div class="row_desc">
					<div class="title">Mô tả:</div>
					<div class="desc">Áo thun tici 4 chiều co giãn, mềm mịn, dày dặn, bla bla bla bla</div>
				</div>
				
			</div>
			<!--End product-description-->
		</div>
		<div class="other-products">
			<div class="title-others">
				<div class="dotted"></div>
				<div class="title">Sản phẩm tương tự</div>
			</div>
				<!--p-item-->
				<div class="slider-details">
					<div class="arrow_slider">
						<a href="javascript:void(0)" class="prev"></a>
						<a href="javascript:void(0)" class="next"></a>
					</div>
					<div class="wrapper-slider">
						<div class="content-slider">
							<div class="p-item">
								<a href="#">
									<img src="<?php echo APP_DOMAIN . '/application/layouts/bookshop/'?>images/s-1.jpg" alt="" title=""/>
									<div class="new"></div><!--new and selloff-->
									<div class="bg-name">
										<p class="name-p">Áo LOTTE Korean 1</p>
										<p class="price">180,000 đ</p>
									</div>
								</a>	
							</div>
							<div class="p-item">
								<a href="#">
									<img src="<?php echo APP_DOMAIN . '/application/layouts/bookshop/'?>images/s-1.jpg" alt="" title=""/>
									<div class="new"></div><!--new and selloff-->
									<div class="bg-name">
										<p class="name-p">Áo LOTTE Korean 2</p>
										<p class="price">180,000 đ</p>
									</div>
								</a>	
							</div>
							<div class="p-item">
								<a href="#">
									<img src="<?php echo APP_DOMAIN . '/application/layouts/bookshop/'?>images/s-1.jpg" alt="" title=""/>
									<div class="new"></div><!--new and selloff-->
									<div class="bg-name">
										<p class="name-p">Áo LOTTE Korean 3</p>
										<p class="price">180,000 đ</p>
									</div>
								</a>	
							</div>
							<!--End p-item-->
							<!--p-item-->
							<div class="p-item">
								<a href="#">
									<img src="<?php echo APP_DOMAIN . '/application/layouts/bookshop/'?>images/s-1.jpg" alt="" title=""/>
									<div class="new"></div><!--new and selloff-->
									<div class="bg-name">
										<p class="name-p">Áo LOTTE Korean 4</p>
										<p class="price">180,000 đ</p>
									</div>
								</a>	
							</div>
							<!--End p-item-->
							<!--p-item-->
							<div class="p-item">
								<a href="#">
									<img src="<?php echo APP_DOMAIN . '/application/layouts/bookshop/'?>images/s-1.jpg" alt="" title=""/>
									<div class="new"></div><!--new and selloff-->
									<div class="bg-name">
										<p class="name-p">Áo LOTTE Korean 4</p>
										<p class="price">180,000 đ</p>
									</div>
								</a>	
							</div>
							<!--End p-item-->
							<!--p-item-->
							<div class="p-item">
								<a href="#">
									<img src="<?php echo APP_DOMAIN . '/application/layouts/bookshop/'?>images/s-1.jpg" alt="" title=""/>
									<div class="new"></div><!--new and selloff-->
									<div class="bg-name">
										<p class="name-p">Áo LOTTE Korean 5</p>
										<p class="price">180,000 đ</p>
									</div>
								</a>	
							</div>
							<!--End p-item-->
						</div>
					</div>
				</div>
		</div>
		<!--comment-product-->
		<div class="comment-product">
			<div class="title-others">
				<div class="dotted"></div>
				<div class="title">Nhận xét của người mua</div>
			</div>
			<div class="fb-comments" data-href="http://hcm.24h.com.vn/bong-da/mu-west-ham-sao-tre-ruc-sang-c48a597613.html" data-width="661" data-numposts="5" data-colorscheme="light"></div>
		</div>
		<!--End comment-product-->
	</div>
	<div class="cart-shop">
		<div class="cart-icon-right">
			<a href="#" class="cart-icon">
				<div class="total">4</div>
			</a>
			<a href="#" class="search-icon"></a>
			<div class="search-content">
				<form method="" action="">
					<input type="text" value="" placeholder="Tìm kiếm" />
				</form>
			</div>
			
			<a href="javascript:void(0);" class="gotoTop"></a>
		</div>
	</div>
	<!--End product-->
</div>