<div class="manage-order">
	<div class="m-top">
		<h3 class="title-page">Tìm kiếm đơn hàng</h3>
	</div>
	<div class="m-bottom">
    	<div class="product product-details">
        
        <p class="find_cart">
        Bạn có thể nhập Mã đơn hàng, Số điện thoại hoặc Email để tìm kiếm đơn hàng bạn đã đặt mua.
        </p>
        <p>
            <input type="text" name="key_find_cart" value="" />
            <a class="btn_find_cart" href="javascript:void(0)">Tìm kiếm</a>
        </p>
        <p class="warning"></p>
    
    
    	</div>
    	<div class="cart-shop">
    		<div class="cart-icon-right">
    			<a class="cart-icon" href="https://socialnetshop.com/apps/apps-store/giohang?idpage=">
    				<div class="total">0</div>
    			</a>
    			<a class="search-icon" href="#"></a>
    			<div class="search-content">
    				<input type="text" placeholder="Tìm kiếm" value="" onkeyup="searchProduct(event, this.value)">
    			</div>
    			
    			<a class="gotoTop" href="javascript:void(0);"></a>
    		</div>
    	</div>
    </div>
</div>