	<div class="commonpage">
        <?php
        	$checkSessionIdpage = $this->checkSessionIdpage;
        	if($checkSessionIdpage == 0)
        	{
        		echo "<center style='color:#41BBDE; padding:20px 0px'>Chọn Page cần thao tác</center>";
        	}
        	else
        	{
        		$idPage = $this->idpage;
        		$config = $this->config;
        ?>
		<form action="<?php echo APP_DOMAIN ?>/admin/config/xulyconfig" method="post" enctype="multipart/form-data" onsubmit="cauhinhapp();">
			<input type="hidden" name="idpage" value="<?php echo $idPage; ?>"/>
			<div class="pageconfig">
				<div class="row">
					<div class="title">Tên shop</div>
					<div class="ip"><input type="text" name="shopname" value="<?php echo @$config[0]['shopname']?>" placeholder="" /></div>
				</div>
				<div class="row">
					<div class="title">Số điện thoại</div>
					<div class="ip"><input type="text" name="phone" value="<?php echo @$config[0]['phone']?>" placeholder="" /></div>
				</div>
				<div class="row">
					<div class="title">Email</div>
					<div class="ip"><input type="text" name="emailfrom" value="<?php echo @$config[0]['emailfrom']?>" placeholder="" /></div>
				</div>
				<div class="row">
					<div class="title">Đơn vị tiền</div>
					<div class="ip"><input type="text" name="donvitien" value="<?php echo (@$config[0]['donvitien'] != "") ? "{$config[0]['donvitien']}" : "VNĐ"; ?>" placeholder="" class="money"/><span class="note">(Mặc định là VNĐ)</span></div>
				</div>
				<div class="row">
					<div class="title">Thông tin liên hệ</div>
					<div class="ip">
                        <textarea  class="textareastyle" name="contact" id="contact"><?php echo @$config[0]['contact'] ?></textarea>
                    </div>
				</div>
				<div class="row">
					<div class="title">Cách thanh toán</div>
					<div class="ip">
                        <textarea  class="textareastyle" name="checkout" id="checkout"><?php echo @$config[0]['checkout'] ?></textarea>
                    </div>
				</div>
                <div class="row">
					<div class="title">Cách giao hàng</div>
					<div class="ip">
                        <textarea  class="textareastyle" name="delivery" id="delivery"><?php echo @$config[0]['delivery'] ?></textarea>
                    </div>
				</div>
				<div class="btn">
                    <input type="submit" name="luucauhinh" value="Lưu cấu hình"/>
                    <input type="button" onclick="top.location.href = '<?php echo ROOT_DOMAIN ?>/admin'" value="Hủy" />
				</div>
		      </div>
          </form>
		<div class="clear"></div>
	</div>





<script>

	var editor1 = CKEDITOR.replace( 'checkout' );
	//CKFinder.setupCKEditor( editor1, '../public/ckfinder/' ) ;

	var editor1 = CKEDITOR.replace( 'delivery' );
	//CKFinder.setupCKEditor( editor1, '../public/ckfinder/' ) ;
    
    var editor1 = CKEDITOR.replace( 'contact' );
    
    var editor1 = CKEDITOR.replace( 'email_cart' );

</script>
<?php } ?>