<?php
    $product = $this->product;
    //print_r($product);exit;
    foreach($product as $key=>$value)
    {
        if(isset($product2))
        {
            $product2[0]['list_idloaisp'][] = $value['idloaisp'];
        }
        else
        {
            $product2[0] = $value;
            $product2[0]['list_idloaisp'][] = $value['idloaisp'];
        }
    }
    $product = $product2;
    $product_hinhanh = $this->product_hinhanh;
    $category = $this->category;
    //print_r($category);
?>
<div class="commonpage">
    <form id='form_update_sanpham' action="" method="post">
		<div class="pageconfig">
			<div class="row">
				<div class="title">Hiển Thị</div>
				<div class="ip">
                    <label><input type="checkbox" value="1" name="hienthi" <?php if($product[0]['anhien']==1) echo "checked='checked'" ?> />
                    (Bỏ chọn nếu không muốn hiển thị sản phẩm này)</label>
                </div>
			</div>
			<div class="row">
				<div class="title">Sản phẩm mới</div>
				<div class="ip">
                    <label><input type="checkbox" value="1" name="spmoi" <?php if($product[0]['spmoi']==1) echo "checked='checked'" ?> />(Chọn nếu muốn hiển thị sản phẩm mới)</label>
                </div>
			</div>
			<div class="row">
				<div class="title">Tên Sản Phẩm</div>
				<div class="ip">
                    <input class="inputstyle" type="text" name="tensp" id="tensp" value="<?php echo $product[0]['tensp'] ?>"/><span style="color: red;">(*)</span>
                </div>
			</div>
			<div class="row">
				<div class="title">Thuộc loại sản phẩm</div>
				<div class="ip">
                <!--
                    <select name='idcat'>
                        <option value="0">Chọn loại sản phẩm</option>
                    <?php 
                        for($i=0; $i<count($category); $i++)
                        {
                    ?>
                        <option value="<?php echo $category[$i]['idloaisp']?>" <?php if($category[$i]['idloaisp']==$product[0]['idloaisp']) echo "selected='selected'" ?>>
                        <?php echo $category[$i]['tenloaisp'] ?></option>
                    <?php } ?>
                    </select>
                -->
                <div class="list_idcat">
                    <?php 
                        for($i=0; $i<count($category); $i++)
                        {
                            if(isset($product[0]['list_idloaisp']))
                            {
                                $checked = in_array($category[$i]['idloaisp'], $product[0]['list_idloaisp']) ? " checked='checked' " : "";
                            }
                            else
                            {
                                $checked = $category[$i]['idloaisp']==$product[0]['idloaisp'] ? " checked='checked' " : "";
                            }
                    ?>
                        <label>
                            <input <?php echo $checked ?> type="checkbox" class="idcat"  name="idcat[]" value="<?php echo $category[$i]['idloaisp']?>" />
                            <span><?php echo $category[$i]['tenloaisp'] ?></span>
                        </label>
                    <?php
                        }
                    ?>
                </div>
                
                
                    <span style="color: red;">(*)</span>
                </div>
			</div>
            <?php
                $hide_giamgia = "";
                if($product[0]['giagiam'] == 0 || $product[0]['giagiam'] == "")
                {
                    $hide_giamgia = "style='display:none'";   
                }
            ?>
			<div class="row">
				<div class="title">Giá Bán</div>
				<div class="ip">
                    <input class="inputstyle" type="text" name="giaban" id="giaban" value="<?php echo $product[0]['gia'] ?>"/><span style="color: red;">(*)</span><br/>
			         <em>(Chỉ nhập số, không có khoảng trắng và ký tự đặc biệt)</em>
                </div>
			</div>
			<div class="row">
				<div class="title">Giảm giá</div>
				<div class="ip">
                    <label>
                        <input <?php if($hide_giamgia == "") echo "checked='checked'" ?> type="checkbox" name="open_giagiam" value="" /> Giảm giá
                    </label>
                </div>
			</div>
            <div class="row div_giagiam" <?php echo $hide_giamgia ?>>
				<div class="title">Giá sau khi giảm</div>
				<div class="ip">
                    <input class="inputstyle" type="text" name="giagiam" id="giagiam" value='<?php echo $product[0]['giagiam'] ?>'/><br/>
			        <em>(Chỉ nhập số, không có khoảng trắng và ký tự đặc biệt)</em>
                </div>
			</div>
            <div class="row div_phantram_giagiam" <?php echo $hide_giamgia ?>>
				<div class="title">Giá giảm (%)</div>
				<div class="ip">
                    <input class="inputstyle" type="text" name="sale_off" id="sale_off" value='<?php echo $product[0]['sale_off'] ?>'/><br/>
			        <em>(Nhập số phần trăm giảm giá)</em>
                </div>
			</div>
            <div class="row">
				<div class="title">Hình ảnh</div>
				<div class="ip">
                    <div class="update_photo_sanpham">
                        <ul class="ul_list_img_fb">
                            <?php
                                if($product[0]['hinhchinh'] != "")
                                {
                            ?>
                            <li class="selected">
                                <label>
                                <p class="img_fb">
                                    <img title="" alt="" src="<?php echo $product[0]['hinhchinh'] ?>">
                                    <input type="radio" value="<?php echo $product[0]['hinhchinh'] ?>" name="photo_sanpham" checked="checked">
                                    <input type="hidden" value="<?php echo $product[0]['hinhchinh'] ?>" name="photo_sanpham_1">
                                    <span>Ảnh chính</span>
                                </p>
                                
                                </label>
                                <input type="text" title="Vị trí hình ảnh hiển thị" value="" name="order_photo_sanpham_1">
                                <a href="javascript:void(0)">
                                    <img title="Xóa Hình" alt="del" src="<?php echo APP_DOMAIN . '/application/templates/giaodien_admin/images/delete.png' ?>">
                                </a>
                            </li>
                            <?php
                                }
                            ?>      
                            
                            <?php
                                $count_photo = 1;
                                foreach($product_hinhanh as $key=>$value)
                                {
                                    $count_photo ++;
                            ?>       
                            <li>
                                <label>
                                <p class="img_fb">
                                    <img title="" alt="" src="<?php echo $value['source'] ?>">
                                    <input type="radio" value="<?php echo $value['source'] ?>" name="photo_sanpham">
                                    <span>Ảnh chính</span>
                                </p>
                                </label>
                                <input type="hidden" value="<?php echo $value['source'] ?>" name="photo_sanpham_<?php echo $count_photo ?>">
                                <input type="text" value="<?php echo $value['sapxep'] ?>" name="order_photo_sanpham_<?php echo $count_photo ?>">
                                <a href="javascript:void(0)">
                                    <img title="Xóa Hình" alt="del" src="<?php echo APP_DOMAIN . '/application/templates/giaodien_admin/images/delete.png' ?>">
                                </a>
                            </li>
                            <?php
                                }
                            ?>
                            
                        </ul>
                        <p style="clear: both; margin-top:10px">
                            <input type="button" onclick="download_photo_fb('update', '6')" name="btn_get_image_on_fb" value="Tải hình">
                        </p>
                    </div>
                </div>
			</div>
            <div class="row">
				<div class="title">Mô tả SP</div>
				<div class="ip">
                    <textarea  class="textareastyle" name="mota" id="mota" ><?php echo $product[0]['mota'] ?></textarea>
                </div>
			</div>
            
			<div class="btn">
                <input type="hidden" name="idsp" value="<?php echo $product[0]['idsp'] ?>" />
                <input type="hidden" name="idpage" value="<?php echo $this->idpage ?>" />
                <input type="button" name="btnsubmit" value="Cập Nhật Sản Phẩm"/>
                <input type="button" onclick="top.location.href = '<?php echo ROOT_DOMAIN ?>/admin/product'" value="Quay lại" />
			</div>
            
		</form>
	</div>
	<div class="clear"></div>
</div>

<script>
	var editor1 = CKEDITOR.replace( 'mota' );
    //tinymce.init({selector:'textarea[name=mota]'});
</script>
























